language: c
compiler:
    - gcc
    - clang
install:
    - "sudo apt-get update"
    - "sudo apt-get install libgtk2.0-dev libmpfr-dev libgmp-dev valgrind python3 rubygems"
    - "sudo gem install ronn"
script:
    - "make -B DEBUG=1 SAFE=1 BAKE=0 CHEEKY=1"
    - "make -B all OPTIM=1 UTF8=1"
    - "sudo make install"
after_script:
    - "make test"
    - "make mtest 2>results && grep 'in use at exit: ' results"
    - "synge-eval --version"
