language: c
compiler:
        - gcc
        - clang
install: "sudo apt-get install libgtk2.0-dev libmpfr-dev libgmp-dev valgrind python3"
script:
        - "make -B debug"
        - "make -B all"
        - "sudo make install"
after_script:
        - "make test"
        - "make mtest 2>results && grep 'in use at exit: ' results"
        - "synge-eval --version"
