language: c
compiler:
        - gcc
        - clang
install: "sudo apt-get install libedit-dev libgtk2.0-dev"
script:
        - "make -B debug"
        - "make -B all"
        - "sudo make install"
after_script:
        - "make test"
        - "synge-eval --version"
